image: archlinux
secrets:
- 3f30fd61-e33d-4198-aafb-0ff341e9db1c
- 3dcea276-38d6-4a7e-85e5-20cbc903e1ea
packages:
  - go
  - yarn
  - podman
  - buildah
environment:
  GONOPROXY: 'git.sr.ht'
sources:
  - https://git.sr.ht/~mariusor/oni
tasks:
  - setup: |
      cd oni && make download && go mod vendor
  - build: |
      cd oni
      make clean oni
  - tests: |
      cd oni
      make test
  - coverage: |
      set -a +x
      cd oni
      make coverage
  - images: |
      test ${BUILD_SUBMITTER} = "git.sr.ht" || complete-build
      set -a +x
      source ~/.buildah.env

      _user=$(id -un)

      echo 'unqualified-search-registries = ["docker.io"]' | sudo tee /etc/containers/registries.conf.d/unq-search.conf
      echo "${_user}:10000:65536" | sudo tee /etc/subuid
      echo "${_user}:10000:65536" | sudo tee /etc/subgid
      podman system migrate

      podman login -u="${BUILDAH_USER}" -p="${BUILDAH_SECRET}" quay.io

      set --
      cd oni || exit

      _sha=$(git rev-parse --short HEAD)
      _branch=$(git branch --points-at=${_sha} | tail -n1 | tr -d '* ')
      _version=$(printf "%s-%s" "${_branch}" "${_sha}")

      make VERSION=${_version} -C images cert builder

      _push() {
        make -C images ENV=dev VERSION="${_version}" push
        if [ "${_branch}" = "master" ]; then
            make -C images ENV=qa VERSION="${_version}" push
        fi

        _tag=$(git describe --long --tags || true)
        if [ -n "${_tag}" ]; then
            make -C images ENV=prod VERSION="${_tag}" push
        fi
      }
      _push
  - push_to_github: |
      test ${BUILD_SUBMITTER} != "git.sr.ht" && complete-build
      set -a +x
      ssh-keyscan -H github.com >> ~/.ssh/known_hosts

      cd oni
      git remote add hub git@github.com:mariusor/oni
      git push hub --force --all
